name: Build
on: [push, release]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5.2
        with:
          registry: ghcr.io
          image: soctorwho/sausage-roles
          username: Emersont1
          password: ${{ secrets.CONTAINER_REGISTRY }}
